work_dir: ntu_ShiftGCN
Experiment_name: NTURGBD_Xsetup

# feeder
feeder: feeders.feeder.Feeder_NTU
train_feeder_args:
  data_path: /home/chehe/Experiments/groupActivity/Shift-GCN/data/ntu120/xsetup/train_data.npy
  label_path: /home/chehe/Experiments/groupActivity/Shift-GCN/data/ntu120/xsetup/train_label.pkl
  debug: False
  self_supervised: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  self_supervised: False
  data_path: /home/chehe/Experiments/groupActivity/Shift-GCN/data/ntu120/xsetup/val_data.npy
  label_path: /home/chehe/Experiments/groupActivity/Shift-GCN/data/ntu120/xsetup/val_label.pkl

# model
model: model.shift_gcn.Model
model_args:
  num_class: 26
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40, 50]

# training
device: 0
only_train_epoch: 1
batch_size: 16
test_batch_size: 16
num_epoch: 60 
nesterov: True
