work_dir: ntu_ShiftGCN_joint_xsubKD_NTURGBDCompleteTeachOccludedMeanImputer_0.6
weights: best_acc.pt

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ../../st-gcn/data/NTURGBDCompleteTeachOccludedMeanImputer_0.6/xsub/train_data.npy
  label_path: ../../st-gcn/data/NTURGBDCompleteTeachOccludedMeanImputer_0.6/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ../../st-gcn/data/NTURGBDCompleteTeachOccludedMeanImputer_0.6/xsub/val_data.npy
  label_path: ../../st-gcn/data/NTURGBDCompleteTeachOccludedMeanImputer_0.6/xsub/val_label.pkl

# model
model: model.shift_gcn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40, 50]

# training
device: 0
only_train_epoch: 1
batch_size: 16
test_batch_size: 16
num_epoch: 55
nesterov: True
