work_dir: ntu_ShiftGCN_joint_phase2
Experiment_name: NTURGBD_phase2

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /mnt/pci-0000:00:17.0-ata-6/ContrastLearning/Shift-GCN/data/pkummd_pre/phase2/train_data.npy
  label_path: /mnt/pci-0000:00:17.0-ata-6/ContrastLearning/Shift-GCN/data/pkummd_pre/phase2/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /mnt/pci-0000:00:17.0-ata-6/ContrastLearning/Shift-GCN/data/pkummd_pre/phase2/val_data.npy
  label_path: /mnt/pci-0000:00:17.0-ata-6/ContrastLearning/Shift-GCN/data/pkummd_pre/phase2/val_label.pkl

# model
model: model.shift_gcn.Model
model_args:
  num_class: 26
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40, 50]

# training
device: 0
only_train_epoch: 1
batch_size: 16
test_batch_size: 16
num_epoch: 55
nesterov: True
